name: touristique_guid
description: A tourist guide app for Southeast Morocco.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.3.0
  firebase_core: ^4.7.0
  firebase_auth: any
  google_sign_in: ^5.4.4
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.1.0
  http: ^1.6.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  flutter_map_cancellable_tile_provider: ^3.1.1
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  uuid: ^4.3.3
  cloudinary_public: ^0.21.0
  path: ^1.8.3
  image_picker: ^1.1.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.jpg
    - assets/images/welcome.jpg
    - assets/images/destination_1.jpg
    - assets/images/destination_2.jpg
    - assets/images/destination_3.jpg
    - assets/images/destination_4.jpg
    - .env
