import '../models/car.dart';

class CarService {
  static List<Car> getCars() {
    return const [
      Car(
        id: '1',
        name: 'Toyota Corolla',
        brand: 'Toyota',
        image: 'assets/images/car1.jpg',
        pricePerDay: 42,
        seats: 5,
        transmission: 'Automatic',
        fuel: 'Petrol',
        company: 'Hertz',
        rating: 4.8,
        luggage: 3,
      ),
      Car(
        id: '2',
        name: 'Hyundai Tucson',
        brand: 'Hyundai',
        image: 'assets/images/car2.jpg',
        pricePerDay: 58,
        seats: 5,
        transmission: 'Automatic',
        fuel: 'Diesel',
        company: 'Avis',
        rating: 4.7,
        luggage: 4,
      ),
      Car(
        id: '3',
        name: 'Dacia Duster',
        brand: 'Dacia',
        image: 'assets/images/car3.jpg',
        pricePerDay: 39,
        seats: 5,
        transmission: 'Manual',
        fuel: 'Diesel',
        company: 'Budget',
        rating: 4.5,
        luggage: 4,
      ),
      Car(
        id: '4',
        name: 'Mercedes C-Class',
        brand: 'Mercedes',
        image: 'assets/images/car4.jpg',
        pricePerDay: 120,
        seats: 5,
        transmission: 'Automatic',
        fuel: 'Petrol',
        company: 'Sixt',
        rating: 4.9,
        luggage: 5,
      ),
      Car(
        id: '5',
        name: 'Volkswagen Golf',
        brand: 'Volkswagen',
        image: 'assets/images/car5.jpg',
        pricePerDay: 55,
        seats: 5,
        transmission: 'Automatic',
        fuel: 'Hybrid',
        company: 'Europcar',
        rating: 4.8,
        luggage: 3,
      ),
      Car(
        id: '6',
        name: 'Peugeot 208',
        brand: 'Peugeot',
        image: 'assets/images/car6.jpg',
        pricePerDay: 37,
        seats: 5,
        transmission: 'Manual',
        fuel: 'Petrol',
        company: 'Keddy',
        rating: 4.6,
        luggage: 2,
      ),
    ];
  }
}