// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNep6dOgmtPXKqoZTHTcLdUh0Ra86OwQ',
    appId: '1:202821805924:web:6414f301b6a4ab508ebc71',
    messagingSenderId: '202821805924',
    projectId: 'touristique-guide-2026',
    authDomain: 'touristique-guide-2026.firebaseapp.com',
    storageBucket: 'touristique-guide-2026.firebasestorage.app',
    measurementId: 'G-B01M9TRDSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFleTNp6O2StyhRPD0F_ZQv1bumqLUCME',
    appId: '1:202821805924:android:fca57062665061b18ebc71',
    messagingSenderId: '202821805924',
    projectId: 'touristique-guide-2026',
    storageBucket: 'touristique-guide-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYh2-pDqYzgltNQwCVzj8wP6Pexqmx0wM',
    appId: '1:202821805924:ios:6115baaad035be348ebc71',
    messagingSenderId: '202821805924',
    projectId: 'touristique-guide-2026',
    storageBucket: 'touristique-guide-2026.firebasestorage.app',
    iosBundleId: 'com.example.touristiqueGuid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYh2-pDqYzgltNQwCVzj8wP6Pexqmx0wM',
    appId: '1:202821805924:ios:6115baaad035be348ebc71',
    messagingSenderId: '202821805924',
    projectId: 'touristique-guide-2026',
    storageBucket: 'touristique-guide-2026.firebasestorage.app',
    iosBundleId: 'com.example.touristiqueGuid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJNep6dOgmtPXKqoZTHTcLdUh0Ra86OwQ',
    appId: '1:202821805924:web:1c6331a2681724e68ebc71',
    messagingSenderId: '202821805924',
    projectId: 'touristique-guide-2026',
    authDomain: 'touristique-guide-2026.firebaseapp.com',
    storageBucket: 'touristique-guide-2026.firebasestorage.app',
    measurementId: 'G-GPZX69RGFS',
  );
}
